### PR TITLE
Switching from POST to GET

### PR DESCRIPTION
**Pull request by joelbarker2011**
In my testing of the list and call commands, POST requests do not work, but GET requests do.

### CODE REVIEW

**Comment by joelbarker2011** [comment]
In my testing of the `list` and `call` commands, `POST` is not working, but `GET` is (caveat: `POST` did work in the `call` command when I accidentally left the `from` parameter blank). Although [RingCentral's documentation](http://service.ringcentral.com/ringoutapi/) clearly states that both `GET` and `POST` are acceptable, this does not seem to be the case.

I did not check or change the other commands (`status` and `cancel`), although it seems reasonable to believe that `GET` should be used for them as well.

**Comment by grokify** [comment]
Hi Joel, I work for RingCentral and just verified that both `GET` and `POST` work successfully for the `list` and `call` (including `from` parameter) commands using cURL. If you are still having issues getting these to work, please post your tests and results here, on StackOverflow, RingCentral Support (http://success.ringcentral.com/) or the RingCentral Community (https://community.ringcentral.com/). Thanks.

**Comment by tfe** [comment]
OK, thanks @grokify. @joelbarker2011, I'm going to close this but feel free to re-open if you find the behavior is not as described.

**Comment by joelbarker2011** [comment]
Sorry to respond late on this, but there are definitely errors when using `POST` (not so with `GET`).

Using `curl` to run the `list` command via `POST`:

``` bash
$ curl 'https://service.ringcentral.com:443/ringout.asp' -d 'cmd=list&username=18661234567&password=mypassword%21&ext='
FAILED Invalid username or password

# maybe the %21 in the password is the problem?
$ curl 'https://service.ringcentral.com:443/ringout.asp' -d 'cmd=list&username=18661234567&password=mypassword!&ext='
FAILED Invalid username or password

# nope, let's trace the request
$ curl 'https://service.ringcentral.com:443/ringout.asp' -d 'cmd=list&username=18661234567&password=mypassword%21&ext=' --trace-ascii -
...
=> Send header, 168 bytes (0xa8)
0000: POST /ringout.asp HTTP/1.1
001c: User-Agent: curl/7.35.0
0035: Host: service.ringcentral.com
0054: Accept: */*
0061: Content-Length: 54
0075: Content-Type: application/x-www-form-urlencoded
00a6: 
=> Send data, 54 bytes (0x36)
0000: cmd=list&username=18661234567&password=mypassword%21
== Info: upload completely sent off: 54 out of 54 bytes
<= Recv header, 17 bytes (0x11)
0000: Server: nginx/1.2.3
0000: Date: Thu, 25 Jun 2015 01:49:06 GMT
0000: Content-Length: 35
0000: Connection: keep-alive
0000: Set-Cookie: RCRoutingInfo=B:e7KJpknUMKtqiDiMKqRRbAPNtiNPZbM9F8OE
0040: 7gzTcbr=; Path=/
0000: Set-Cookie: SCS_ROUTE=906ba8ea368e1ceffc5e66cfd5342754; Path=/
0000: x-frame-options: sameorigin
0000: x-xss-protection: 1; mode=block
0000: Set-Cookie: RCRoutingAdvice=CLGX2SZJRMC5W; Path=/
0000: Set-Cookie: JSESSIONID=-SjlgtVJ2l+yUFSqHHrvFZQ8; Path=/
0000: 
<= Recv data, 35 bytes (0x23)
0000: FAILED Invalid username or password
FAILED Invalid username or password== Info: Connection #0 to host service.ringcentral.com left intact
```

Now using `GET`:

``` bash
$ curl 'https://service.ringcentral.com:443/ringout.asp' -d 'cmd=list&username=18661234567&password=mypassword%21&ext=' -G
OK 6611234567;Home;6611234567;Office;8601234567;Paul

# use a literal ! for good measure
$ curl 'https://service.ringcentral.com:443/ringout.asp' -d 'cmd=list&username=18661234567&password=mypassword!&ext=' -G
OK 6611234567;Home;6611234567;Office;8601234567;Paul
```

**Pull request closed without merging**
